---
- hosts: localhost
  become: true
    
  tasks:
    - name: Install Base
      pacman:
        name:
          - linux-headers
          - xclip
          - wget
          - git
          - curl
          - gnupg
          - fontconfig
          - unzip
          - tmux
          - nodejs
          - xwallpaper
          - stow
          - neovim
          - exa
          - keepassxc
          - mpv
          - yt-dlp
          - signal-desktop
          - dunst
          - libnotify
          - ntfs-3g

        state: present
...
