---
- hosts: localhost
  become: true
    
  tasks:
    - name: Install Base
      pacman:
        name:
          - linux-headers
          - wget
          - git
          - curl
          - gnupg
          - fontconfig
          - unzip
          - tmux
          - nodejs
          - xwallpaper
          - stow
          - neovim
          - exa
          - keepassxc
          - nvidia-dkms
        state: present
...
