---
- name: Set up GitHub SSH keys
  hosts: localhost
  vars_files:
    - vars/sec.yml
  vars:
    git_username: "Pablo - Flux"
    git_email: pablo@renderbros.com
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
      become: yes
      become_user: pablo

    - name: Copy GitHub SSH private key
      copy:
        content: "{{ github_private_key }}"
        dest: "~/.ssh/github-ssh"
        mode: 0600
      become: yes
      become_user: pablo

    - name: Copy gitconfig to user's home directory
      template:
        src: templates/.gitconfig.j2
        dest: "~/.gitconfig"
      become: yes
      become_user: pablo

