- hosts: localhost
  become: no
  tasks:
    - name: Install Dependancies
      become: yes
      pacman:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - libx11
          - libxinerama
          - libxft
          - freetype2
          - fontconfig
          - make
          - gcc
          - xorg
          - xorg-server
          - xorg-xinit
          - git
          - firefox
          - alacritty
          - ttf-roboto-mono-nerd
          - ttf-terminus-nerd
          - unclutter

        #    - name: Check if suckless folder exists
        #      stat:
        #        path: "~/bin/suckless"
        #      register: suckless_folder
        #
        #    - name: Clone Dwm repo
        #      git:
        #        repo: 'https://github.com/harryhosepipe/suckless.git'
        #        dest: "~/bin/suckless"
        #        clone: yes
        #        update: yes
        #      become: yes
        #      become_user: pablo
        #      when: not suckless_folder.stat.exists

    - name: Compile and build dwm
      shell: make clean install
      args:
        chdir: "~/bin/suckless/dwm"
      become: yes
      become_user: pablo

    - name: Compile and build dwmblocks
      shell: make clean install
      args:
        chdir: "~/bin/suckless/dwmblocks"
      become: yes
      become_user: pablo

    - name: Compile and build dmenu
      shell: make clean install
      args:
        chdir: "~/bin/suckless/dmenu"
      become: yes
      become_user: pablo
