---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    pacman:
      update_cache: yes
      
  - name: Install Samba server 
    pacman:
      name: samba
      state: latest

  - name: Create samba group
    group:
      name: sambausers
      state: present
      system: yes

  - name: Add pablo to sambausers group
    user: 
      name: 'pablo'
      groups: sambausers
      append: yes 

  - name: Make Samba password
    expect:
      shell:
      cmd: echo -ne "1234\n1234\n" | smbpasswd -a -s pablo
      
