---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Setup Vim 
    package:
      name: vim
  
  - name: copy vim rc
    copy:
      src: configs/.vimrc
      dest: /home/pablo/
      owner: pablo
      group: pablo
