---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Setup Vim 
    package:
      name: vim
  
  - name: copy vim rc
    copy:
      src: configs/.vimrc
      dest: /home/pablo/.vimrc force=no
      owner: pablo
      group: pablo

  - name: make vim plugin folder
    file:
      path: /home/pablo/.vim/autoload
      state: directory
      owner: pablo
      group: pablo

  - name: download vim plugin manager
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/pablo/.vim/autoload/plug.vim
      owner: pablo
      group: pablo

  - name: setup rtorrent
    package:
      name: rtorrent

  - name: copy rtorrent configs
    copy:
      src: configs/.rtorrent.rc
      dest: /home/pablo/.rtorrent.rc
      owner: pablo
      group: pablo

  - name: make rtorrent folders
    file:
      path: /home/pablo/Downloads/rdown
      path: /home/pablo/Downloads/rsession
      path: /home/pablo/Downloads/rwatch
      state: directory

# symlink example
#
#  - name: smylink demo
#    hosts: all
#    vars:
#      mysrc: "~/slingshot"
#      mydes: "~/"
#    tasks:
#      -name: create symlink
#       ansible.builtin.file:
#         src: "{{ mysrc }}
#         dest: "{{ mydes }}"
#         state: link
