- name: PRIME THE SYSTEM BRO!
  hosts: localhost
  become: yes
  
  tasks:

  - name: Run stow command in specific directory
    ansible.builtin.shell:
      cmd: sudo stow --adopt -t /etc/X11 X11
      chdir: "/home/pablo/slingshot/xorg/"
    become: yes

